import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Define the font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Seedlist.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body suppressHydrationWarning className="max-w-full mx-auto">
        {children}
      </body>
    </html>
  );
}
